#!/usr/bin/env python

import logging
from flask.ext.script import Manager
from mediasearch.web import create
from functools import partial


if __name__ == '__main__':

    logging.basicConfig(level=logging.DEBUG)
    logging.captureWarnings(True)

    class C(object):

        SITE_TITLE = 'Mediasearch'
        SECRET_KEY = 'secret'

    configured_create = partial(
        create,
        config=C(),
    )

    manager = Manager(configured_create)
    manager.run()
