#!/usr/bin/env python

from gevent import monkey
monkey.patch_all()


import logging

from functools import partial
from flask.ext.script import Manager
from mediasearch.web import create
from mediasearch.commands import GeventServer


if __name__ == '__main__':

    logging.basicConfig(level=logging.DEBUG)
    logging.captureWarnings(True)

    class Config(object):

        DEBUG = True
        SITE_TITLE = 'Mediasearch'
        SECRET_KEY = 'secret'
        DATABASE = 'database'

    configured_create = partial(
        create,
        config=Config(),
    )

    geventserver = GeventServer()

    manager = Manager(configured_create)
    manager.add_command('rungeventserver', geventserver)
    manager.run()
